spring.application.name: product-api
spring.profiles.active: local

jwt:
  secret: ${JWT_SECRET:ZmFrZS1sb2NhbC1zZWNyZXQZmFrZS1sb2NhbC1zZWNyZXQZmFrZS1sb2NhbC1zZWNyZXQZmFrZS1sb2NhbC1zZWNyZXQ}
  access-expiration-ms: ${JWT_ACCESS_EXPIRATION_MS:900000} # 15분
  refresh-expiration-ms: ${JWT_REFRESH_EXPIRATION_MS:604800000} # 7일

---
spring.config.activate.on-profile: local

---
spring.config.activate.on-profile: local-dev

---
spring.config.activate.on-profile: dev

---
spring.config.activate.on-profile: live
