spring.application.name: product-api
spring.profiles.active: local

jwt:
  secret: ${JWT_SECRET:ZmFrZS1sb2NhbC1zZWNyZXQZmFrZS1sb2NhbC1zZWNyZXQZmFrZS1sb2NhbC1zZWNyZXQZmFrZS1sb2NhbC1zZWNyZXQ}
  access-expiration-ms: ${JWT_ACCESS_EXPIRATION_MS:900000} # 15분
  refresh-expiration-ms: ${JWT_REFRESH_EXPIRATION_MS:604800000} # 7일

---
spring.config.activate.on-profile: local

spring:
  datasource:
    url: jdbc:h2:mem:productdb;MODE=MySQL;NON_KEYWORDS=USER;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

---
spring.config.activate.on-profile: local-dev

---
spring.config.activate.on-profile: dev

---
spring.config.activate.on-profile: live
